name: PA3 CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, linux]
    container: ubuntu:latest
    timeout-minutes: 3
    steps:
      - name: Install build dependencies
        run: |
          apt update
          apt install -y build-essential cmake

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure and build project
        run: |
          cmake -S . -B build
          cmake --build build

  test:
    runs-on: [self-hosted, linux]
    container: ubuntu:latest
    timeout-minutes: 5
    steps:
      - name: Install test dependencies
        run: |
          apt update
          apt install -y build-essential cmake libgtest-dev

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and run tests
        run: |
          cmake -S . -B build
          cmake --build build
          cd build && ctest --output-on-failure

  lint:
    runs-on: [self-hosted, linux]
    container: ubuntu:latest
    timeout-minutes: 3
    steps:
      - name: Install linter
        run: |
          apt update
          apt install -y clang-tidy

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run clang-tidy
        run: clang-tidy PA3.cpp Main.cpp -- -std=c++17

  deploy:
    runs-on: [self-hosted, linux]
    container: ubuntu:latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker and SSH tools
        run: |
          apt update
          apt install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release \
            openssh-client

          mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/debian/gpg | \
            gpg --dearmor -o /etc/apt/keyrings/docker.gpg

          echo \
            "deb [arch=$(dpkg --print-architecture) \
            signed-by=/etc/apt/keyrings/docker.gpg] \
            https://download.docker.com/linux/debian \
            $(lsb_release -cs) stable" | \
            tee /etc/apt/sources.list.d/docker.list > /dev/null

          apt update
          apt install -y docker-ce docker-ce-cli containerd docker-buildx-plugin

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.REMOTE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Build Docker image
        run: docker build -t pa3-project .

      - name: Save and transfer Docker image to remote host
        run: |
          docker save pa3-project | gzip > pa3-project.tar.gz
          scp pa3-project.tar.gz ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/tmp/

      - name: Run container on remote host
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} '
            gunzip /tmp/pa3-project.tar.gz &&
            docker load < /tmp/pa3-project.tar &&
            docker run --rm pa3-project
          '
