name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev libpthread-stubs0-dev

      - name: Build GTest
        run: |
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/

  test:
    name: Test
    runs-on: self-hosted
    needs: build
    timeout-minutes: 4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build

      - name: Run unit tests
        run: ./build/runTests

  lint:
    name: Lint
    runs-on: self-hosted
    needs: build
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Clang-Tidy
        run: sudo apt-get install -y clang-tidy

      - name: Run Clang-Tidy
        run: clang-tidy PA4.cpp PA4.h Main.cpp -- -I.

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: [test, lint]
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker
        run: sudo apt-get install -y docker.io

      - name: Build Docker image
        run: docker build -t pa4-app .

      - name: Save Docker image as artifact
        run: |
          docker save pa4-app > pa4-app.tar
          mkdir -p artifacts
          mv pa4-app.tar artifacts/

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: artifacts/pa4-app.tar